language: node_js

node_js:
  - 'node'

script:
  - npm run build

deploy:
  github_token: $GITHUB_TOKEN
  keep_history: true
  local-dir: dist
  on:
    branch: master
  provider: pages
  skip_cleanup: true
